### ISSUE TITLE
How to dynamically set run time of task?

### ISSUE THREAD

**Issue by sachin-nagarro** [tomykaira/clockwork#145]
This is my clock.rb

```ruby
require 'clockwork'
require './config/boot'
require './config/environment'

module Clockwork
  handler do |job|
    puts "Running #{job}"
  end

  cron_time = ApplicationConfig.first.cron_time
  every(cron_time.minutes, 'fetching recent bookings'){
    `rake update_bookings`
  }

end
```

here after deployment a user can change `cron_time` as per his need is it possible to make it dynamic by any means?

**Comment by tomykaira** [comment]
Sorry for late response.

Of course, but `cron_time` must fix when `clockwork` starts, because `every()` takes `cron_time.minutes` and it is a value, not a variable.
If you want to change duration while clockwork is running, [`:if` option](https://github.com/tomykaira/clockwork#if) is the solution, but it is not straight forward.
For example,

```
every(1.seconds, 'fetching recent bookings', if: lambda { |current_time| ApplicationConfig.time_to_run?(current_time) }) do
  `rake update_bookings`
end
```

It may seem like clockwork does nothing.

**Comment by sachin-nagarro** [comment]
@tomykaira Thanks i will try it.
