### ISSUE TITLE
How to set monthly scheduler for database events?

### ISSUE THREAD

**Issue by paramaw** [tomykaira/clockwork#147]
Hi there,

How do we set a monthly scheduler for database based events that use sync_database_events method?
I've read #89 but it doesn't answer my question above.

Thanks.

**Comment by robisenberg** [comment]
With non-database backed events, if you wanted an event to fire on the first day of every month (for example), I think you'd be doing this:

```
every(1.day, 'some.task', if: ->{|time| time.beginning_of_month == time.beginning_of_day}) 
```

This event tries to run every day, but the `if` means that it will only actually be allowed to execute if the the datetime it fires at happens to occur happens to be the first day of the month.

Now, [as said previously](https://github.com/tomykaira/clockwork/issues/113) the standard Clockwork `:if` doesn't translate well to database-backed events because it allows for _arbitrary_ code execution. However, you can implement this custom behaviour yourself, by doing something like the following (I'm using Delayed Job as and example, but it's really the `if run_event_today?` part that is the important bit)...

First, your database event model could have a field `days_to_run_event_on:String` which you could be a comma-separatated list (there are lots of ways to model this). So, for example, if you wanted a particular event to run on the first and fifth day of the month, you'd do `event.only_run_event_on_days == '1,5'`.

Then in your `clock.rb` you'd do:

```
require 'clockwork'
require 'clockwork/database_events'
require_relative './config/boot'
require_relative './config/environment'

module Clockwork

  # required to enable database syncing support
  Clockwork.manager = DatabaseEvents::Manager.new

  def comma_separated_integer_string_to_integer_array integer_csv_string
    integer_csv_string.split(',').map{|string_int| Integer(string_int)}
  end

  def run_event_today? integer_csv_string
    !model_instance.only_run_event_on_days || comma_separated_integer_string_to_integer_array(integer_cv_string).include(Time.now.day_of_month)
  end

  sync_database_events model: ClockworkDatabaseEvent, every: 1.minute do |model_instance|
    model_instance.delay.some_action if run_event_today?
  end
end
```

Does that make sense? Essentially, the approach is:

1. Store whatever fields you need in your model to distinguish the times/days you do/don't want the event to run
2. Set your `sync_database_events` call to run *more* frequently than you actually want the events to run (it must happen frequently enough so that the event would actually attempt fire on the day/time you want, ensuring that `sync_database_events` block gets called)
3. Add some extra logic inside the `sync_database_events` handler block to check whether to allow the event to run based on those model fields you added in step 1

Hope that makes sense and helps.

**Comment by paramaw** [comment]
This Works. Awesome!

Thanks!

**Comment by robisenberg** [comment]
Hey @paramaw. I know it's been a long time, and I know you got it working the way I suggested above. However, I thought it was worth mentioning that we've just implemented `:if` support for database-backed events. Checkout the README for details of a better way to do this now. :smile:

**Comment by paramaw** [comment]
Interesting. 

Thanks for letting me know. I'll check it out
