### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by robisenberg** [tomykaira/clockwork#160]
Hi @tomykaira - hope you're doing well. Sorry, I have a couple of outstanding issues that I need to sort out relating to database-backed events. I've been a bit snowed under with work recently and am only just getting round to this now.

I was trying to respond to #157, but when I update to the latest `master` and run the tests it seems that they aren't all running:

```
$ bundle exec rake test
Loaded suite /Users/robisenberg/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader
Started
....................................

Finished in 0.034154 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
36 tests, 89 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
16.6667% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1054.05 tests/s, 2605.84 assertions/s
```

I can see that:
1. only 36 tests get run, but there are many more than that
2. the 16.6667% passed is a little weird

If I now just run, say, the `manager_test.rb`:

```
$ bundle exec rake test TEST=test/manager_test.rb 
Loaded suite /Users/robisenberg/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader
Started
.................

Finished in 0.018632 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
17 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
912.41 tests/s, 1824.82 assertions/s
```

Firstly, the `0% passed` is even more weird, but also only 17 tests are being run out of the 41 in the file. It appears that tests inside a `describe` block are being ignored (similar to this https://github.com/metaskills/mini_specunit/issues/1).

I'm not sure if I'm doing something wrong (entirely possible!) or whether I'm missing something. Are you able to help?

**Comment by summera** [comment]
@robisenberg @tomykaira  
I was trying to contribute and ran into this problem as well. Looking through the previous builds on Travis CI it looks like https://github.com/tomykaira/clockwork/pull/139 is the culprit. 

Before build https://travis-ci.org/tomykaira/clockwork/jobs/48643634 it looks like all tests were running. However once the patch for Ruby 2.2 was introduced, a bunch of tests stopped running.

I think maybe refactoring the tests so you aren't depending on ActiveSupport::TestCase, Minitest, and TestUnit will fix the problem here. Maybe just using minitest unless there is a reason for an additional dependency? Also maybe locking these down to a minor version could help with future conflicts. Thoughts?
